# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rep.ajax.toolkit"
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher York", "Dave Della Costa"]
  s.date = "2012-04-14"
  s.description = "Hyperstudio ajax tools"
  s.email = "dfd@mit.edu"
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "TODO"
  ]
  s.files = [
    "LICENSE",
    "README",
    "Rakefile",
    "TODO",
    "VERSION",
    "lib/rep.ajax.toolkit.rb",
    "rep.ajax.toolkit.gemspec"
  ]
  s.homepage = "http://github.com/repertoire/rep.ajax.toolkit"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Hyperstudio ajax tools"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

